"use client";

import { nanoid } from "nanoid";
import { Product } from "./Columns";
import {
  MdInventory,
  MdBuild,
  MdPhoneIphone,
  MdLaptop,
  MdKitchen,
  MdHome,
  MdChair,
  MdLightbulbCircle,
  MdOutlineDoorSliding,
} from "react-icons/md";
import { FaBed, FaHeadphones, FaTv } from "react-icons/fa";
import { IoTabletPortrait } from "react-icons/io5";
import { GiSofa } from "react-icons/gi";

export const products: Product[] = [
  {
    id: nanoid(),
    name: "Obeng",
    supplier: "ToolSupplier Inc.",
    sku: "SD123",
    category: "Others",
    status: "Draft",
    quantityInStock: 50,
    price: 195000,
    icon: <MdBuild />,
    createdAt: new Date("2023-01-15"),
  },
  {
    id: nanoid(),
    name: "Palu",
    supplier: "ToolSupplier Inc.",
    sku: "HM456",
    category: "Others",
    status: "Published",
    quantityInStock: 30,
    price: 232500,
    icon: <MdInventory />,
    createdAt: new Date("2023-02-10"),
  },
  {
    id: nanoid(),
    name: "Smartphone",
    supplier: "TechWorld",
    sku: "SP789",
    category: "Electronics",
    status: "Published",
    quantityInStock: 100,
    price: 7495000,
    icon: <MdPhoneIphone />,
    createdAt: new Date("2023-03-05"),
  },
  {
    id: nanoid(),
    name: "Laptop",
    supplier: "TechWorld",
    sku: "LT101",
    category: "Electronics",
    status: "Inactive",
    quantityInStock: 25,
    price: 13499900,
    icon: <MdLaptop />,
    createdAt: new Date("2023-04-20"),
  },
  {
    id: nanoid(),
    name: "Microwave Oven",
    supplier: "HomeGoods Co.",
    sku: "MO202",
    category: "Furniture",
    status: "Draft",
    quantityInStock: 15,
    price: 1800000,
    icon: <MdKitchen />,
    createdAt: new Date("2023-05-18"),
  },
  {
    id: nanoid(),
    name: "Mesin Cuci",
    supplier: "HomeGoods Co.",
    sku: "WM303",
    category: "Home Decor",
    status: "Published",
    quantityInStock: 10,
    price: 6750000,
    icon: <MdHome />,
    createdAt: new Date("2023-06-22"),
  },
  {
    id: nanoid(),
    name: "Kulkas",
    supplier: "HomeGoods Co.",
    sku: "RF404",
    category: "Home Appliances",
    status: "Inactive",
    quantityInStock: 8,
    price: 11999900,
    icon: <MdKitchen />,
    createdAt: new Date("2023-07-10"),
  },
  {
    id: nanoid(),
    name: "Tablet",
    supplier: "TechWorld",
    sku: "TB505",
    category: "Electronics",
    status: "Draft",
    quantityInStock: 60,
    price: 2990000,
    icon: <MdLaptop />,
    createdAt: new Date("2023-08-15"),
  },
  {
    id: nanoid(),
    name: "Headphone",
    supplier: "AudioTech",
    sku: "HP601",
    category: "Electronics",
    status: "Published",
    quantityInStock: 40,
    price: 1200000,
    icon: <FaHeadphones />,
    createdAt: new Date("2023-09-01"),
  },
  {
    id: nanoid(),
    name: "Kursi Kantor",
    supplier: "FurnitureGalore",
    sku: "OC702",
    category: "Furniture",
    status: "Inactive",
    quantityInStock: 20,
    price: 2249999,
    icon: <MdChair />,
    createdAt: new Date("2023-10-12"),
  },
  {
    id: nanoid(),
    name: "Lampu Meja",
    supplier: "HomeGoods Co.",
    sku: "DL803",
    category: "Electronics",
    status: "Draft",
    quantityInStock: 30,
    price: 525000,
    icon: <MdLightbulbCircle />,
    createdAt: new Date("2023-11-05"),
  },
  {
    id: nanoid(),
    name: "Mouse Gaming",
    supplier: "TechWorld",
    sku: "GM904",
    category: "Electronics",
    status: "Published",
    quantityInStock: 55,
    price: 900000,
    icon: <MdHome />,
    createdAt: new Date("2023-12-01"),
  },
  {
    id: nanoid(),
    name: "Pemanas Air Listrik",
    supplier: "HomeGoods Co.",
    sku: "EK105",
    category: "Home Appliances",
    status: "Draft",
    quantityInStock: 25,
    price: 599000,
    icon: <MdKitchen />,
    createdAt: new Date("2024-01-08"),
  },
  {
    id: nanoid(),
    name: "Grill Luar Ruangan",
    supplier: "HomeDepot",
    sku: "OG206",
    category: "Furniture",
    status: "Published",
    quantityInStock: 15,
    price: 3749999,
    icon: <MdOutlineDoorSliding />,
    createdAt: new Date("2024-02-14"),
  },
  {
    id: nanoid(),
    name: "Bor Nirkabel",
    supplier: "ToolSupplier Inc.",
    sku: "CD307",
    category: "Others",
    status: "Inactive",
    quantityInStock: 35,
    price: 1499999,
    icon: <MdBuild />,
    createdAt: new Date("2024-03-22"),
  },
  {
    id: nanoid(),
    name: "Smart TV",
    supplier: "TechWorld",
    sku: "ST408",
    category: "Electronics",
    status: "Draft",
    quantityInStock: 22,
    price: 8990000,
    icon: <FaTv />,
    createdAt: new Date("2024-04-30"),
  },
  {
    id: nanoid(),
    name: "Meja Makan",
    supplier: "FurnitureGalore",
    sku: "DT509",
    category: "Furniture",
    status: "Published",
    quantityInStock: 8,
    price: 5999999,
    icon: <IoTabletPortrait />,
    createdAt: new Date("2024-05-18"),
  },
  {
    id: nanoid(),
    name: "Earbuds Nirkabel",
    supplier: "AudioTech",
    sku: "WE610",
    category: "Electronics",
    status: "Inactive",
    quantityInStock: 45,
    price: 1499999,
    icon: <FaHeadphones />,
    createdAt: new Date("2024-06-25"),
  },
  {
    id: nanoid(),
    name: "Dekorasi Dinding",
    supplier: "HomeGoods Co.",
    sku: "WD711",
    category: "Home Decor",
    status: "Draft",
    quantityInStock: 18,
    price: 449999,
    icon: <GiSofa />,
    createdAt: new Date("2024-07-03"),
  },
  {
    id: nanoid(),
    name: "Set Furnitur Outdoor",
    supplier: "FurnitureGalore",
    sku: "OF812",
    category: "Furniture",
    status: "Published",
    quantityInStock: 12,
    price: 11999999,
    icon: <FaBed />,
    createdAt: new Date("2024-08-11"),
  },
];
